Integrate pylint-exit for error handling

diff --git a/.github/workflows/pylintServer.yml b/.github/workflows/pylintServer.yml
--- a/.github/workflows/pylintServer.yml
+++ b/.github/workflows/pylintServer.yml
@@ -27,6 +27,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install pylint
+          pip install pylint-exit
           pip install -r requirements.txt
 
       - name: Run insert_pylint_directives.py script
@@ -37,12 +38,15 @@ jobs:
           FILES=$(git ls-files 'swagger_server/**/*.py' | grep -v '/test/')
           if [ -f .pylintrc ]; then
             echo "pylint --rcfile=.pylintrc $FILES --output-format=text:lint.txt,colorized" 
-            pylint --rcfile=.pylintrc $FILES --output-format=text:lint.txt,colorized
+            pylint --rcfile=.pylintrc $FILES --output-format=text:lint.txt,colorized || pylint-exit $?
           else
             echo "pylint $FILES --output-format=text:lint.txt,colorized"
-            pylint $FILES --output-format=text:lint.txt,colorized
+            pylint $FILES --output-format=text:lint.txt,colorized || pylint-exit $?
           fi
-          echo "Pylint completed"
+          if [ $? -ne 0 ]; then
+            echo "An error occurred while running pylint." >&2
+            exit 1
+          fi
           
       - name: Upload lint results as artifact
         uses: actions/upload-artifact@v4
